/*
 * This source file was generated by the Gradle 'init' task
 */
package nedterminal;

public class App {
    public String getGreeting() {
        return "Welcome back, Chlorine levels stable. What are we doing today?";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
